src/Spolischook/MiniShopBundle/Entity/ProductSale.php
<?php

namespace Spolischook\MiniShopBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Context\ExecutionContextInterface;

/**
 * ProductSales
 *
 * @ORM\Table(name="product_sale")
 * @ORM\Entity(repositoryClass="Spolischook\MiniShopBundle\Repository\ProductSaleRepository")
 * @ORM\HasLifecycleCallbacks()
 * @Gedmo\SoftDeleteable(fieldName="deletedAt", timeAware=false)
 */
class ProductSale implements ItemMovingInterface
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var \Spolischook\MiniShopBundle\Entity\Store
     *
     * @ORM\ManyToOne(targetEntity="Spolischook\MiniShopBundle\Entity\Store", inversedBy="productSales", fetch="EAGER")
     */
    private $store;

    /**
     * @var integer
     *
     * @Assert\Type(type="integer")
     * @Assert\NotBlank()
     * @ORM\Column(name="quantity", type="integer")
     */
    private $quantity;

    /**
     * @var integer
     *
     * @Assert\Type(type="integer")
     * @Assert\NotBlank()
     * @ORM\Column(name="price", type="integer")
     */
    private $price;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="created_at", type="datetime")
     * @Gedmo\Timestampable(on="create")
     */
    private $createdAt;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="deletedAt", type="datetime", nullable=true)
     */
    private $deletedAt;

    /**
     * @var string
     *
     * @ORM\Column(name="comment", type="string", length=255, nullable=true)
     */
    private $comment;

    /**
     * @var string
     *
     * @Assert\NotBlank()
     * @Assert\Choice(callback = {"Spolischook\MiniShopBundle\Entity\Bank", "getAllowedTypes"}, message = "Allowed 'card' or 'cash'")
     * @ORM\ManyToOne(targetEntity="Spolischook\MiniShopBundle\Entity\Bank", inversedBy="salesTransactions", fetch="EAGER")
     */
    private $bank;

    /**
     * @var string
     * @deprecated
     * @ORM\Column(name="method_of_payment", type="string", length=255, nullable=true)
     */
    private $methodOfPayment = null;

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set quantity
     *
     * @param integer $quantity
     * @return ProductSale
     */
    public function setQuantity($quantity)
    {
        $this->quantity = $quantity;

        return $this;
    }

    /**
     * Get quantity
     *
     * @return integer
     */
    public function getQuantity()
    {
        return $this->quantity;
    }

    /**
     * Set price
     *
     * @param integer $price
     * @return ProductSale
     */
    public function setPrice($price)
    {
        $this->price = $price;

        return $this;
    }

    /**
     * Get price
     *
     * @return integer 
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * Set createdAt
     *
     * @param \DateTime $createdAt
     * @return ProductSale
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * Get createdAt
     *
     * @return \DateTime 
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Set comment
     *
     * @param string $comment
     * @return ProductSale
     */
    public function setComment($comment)
    {
        $this->comment = $comment;

        return $this;
    }

    /**
     * Get comment
     *
     * @return string 
     */
    public function getComment()
    {
        return $this->comment;
    }

    /**
     * Set store
     *
     * @param \Spolischook\MiniShopBundle\Entity\Store $store
     * @return ProductSale
     */
    public function setStore(Store $store = null)
    {
        $this->store = $store;

        return $this;
    }

    /**
     * Get store
     *
     * @return \Spolischook\MiniShopBundle\Entity\Store 
     */
    public function getStore()
    {
        return $this->store;
    }

    /**
     * @return string
     */
    public function getFrom()
    {
        return $this->getStore()->getTitle();
    }

    /**
     * @return string
     */
    public function getTo()
    {
        return $this->getComment();
    }

    /**
     * Set bank
     *
     * @param \Spolischook\MiniShopBundle\Entity\Bank $bank
     * @return ProductSale
     */
    public function setBank(\Spolischook\MiniShopBundle\Entity\Bank $bank = null)
    {
        $this->bank = $bank;

        return $this;
    }

    /**
     * Get bank
     *
     * @return \Spolischook\MiniShopBundle\Entity\Bank 
     */
    public function getBank()
    {
        return $this->bank;
    }

    /**
     * Set methodOfPayment
     * @deprecated
     * @param string $methodOfPayment
     * @return ProductSale
     */
    public function setMethodOfPayment($methodOfPayment)
    {
        $this->methodOfPayment = $methodOfPayment;

        return $this;
    }

    /**
     * Get methodOfPayment
     * @deprecated
     * @return string 
     */
    public function getMethodOfPayment()
    {
        return $this->methodOfPayment;
    }

    /**
     * @return string
     */
    public function getRouterChunkClassName()
    {
        return 'productsale';
    }

    /**
     * Set deletedAt
     *
     * @param \DateTime $deletedAt
     * @return ProductSale
     */
    public function setDeletedAt($deletedAt)
    {
        $this->deletedAt = $deletedAt;

        return $this;
    }

    /**
     * Get deletedAt
     *
     * @return \DateTime 
     */
    public function getDeletedAt()
    {
        return $this->deletedAt;
    }

    /**
     * @Assert\Callback
     */
    public function validateStoreQuantity(ExecutionContextInterface $context)
    {
        if ($this->getStore()->getProductQuantity() - $this->getQuantity() < 0) {
            $context->buildViolation('Not enough goods in a store')
                ->atPath('quantity')
                ->addViolation();
        }
    }
}

src/Spolischook/MiniShopBundle/Controller/ProductMovingController.php
<?php

namespace Spolischook\MiniShopBundle\Controller;

use Spolischook\MiniShopBundle\Entity\ItemMovingInterface;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Symfony\Component\Serializer\Serializer;
use Symfony\Component\Serializer\Encoder\XmlEncoder;
use Symfony\Component\Serializer\Encoder\JsonEncoder;
use Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer;

class ProductMovingController extends Controller
{
    /**
     * @Template()
     * @Route("/product-moving")
     * @Method({"GET"})
     */
    public function getAllMovingAction()
    {
        $productMovings = array_merge(
//            $this->getDoctrine()->getManager()->getRepository('MiniShopBundle:ProductSale')->findAll(),
            $this->getDoctrine()->getManager()->getRepository('MiniShopBundle:ProductTransfer')->findAll()
//            $this->getDoctrine()->getManager()->getRepository('MiniShopBundle:MoneyTransfer')->findAll()
        );

        usort($productMovings, array($this, "compareDateTime"));

        return ['productMovings' => $this->container->get('jms_serializer')->serialize(['productMovings' => $productMovings], 'json')];
    }

    public function compareDateTime(ItemMovingInterface $a, ItemMovingInterface $b)
    {
        if ($a->getCreatedAt() == $b->getCreatedAt()) {
            return 0;
        }

        return ($a->getCreatedAt() > $b->getCreatedAt()) ? +1 : -1;
    }
}

src/Spolischook/MiniShopBundle/Resources/views/ProductMoving/getAllMoving.html.twig
{% extends '::base.html.twig' %}

{% block title %}Движение товаров{% endblock %}
{% block container %}
    <h2>Движение товаров</h2>
    <div id="view-data"></div>
    <div class="row">
        <div class="col-md-10">
            <table class="table">
                <tr>
                    <th>Дата</th>
                    <th></th>
                    <th>From</th>
                    <th></th>
                    <th>To</th>
                    <th>Количество</th>
                    <th>Actions</th>
                </tr>
                {% for productMoving in productMovings %}
                    {% if loop.first %}
                        <tr><td colspan="7"><h4>{{ productMoving.createdAt|date('F') }}</h4></td></tr>
                    {% elseif productMoving.createdAt|date('F') != previousProductMoving.createdAt|date('F') %}
                        <tr><td colspan="7"><h4>{{ productMoving.createdAt|date('F') }}</h4></td></tr>
                    {% endif %}
                        <tr class="product-moving-data">
                            <td>
                                {% if loop.first or productMoving.createdAt|date("Y-m-d") != previousProductMoving.createdAt|date("Y-m-d") %}
                                    {{ productMoving.createdAt|date("Y-m-d") }}
                                {% endif %}
                            </td>
                            <td><span class="glyphicon glyphicon-{{ getIconName(productMoving) }}" aria-hidden="true"></span></td>
                            <td>{{ productMoving.from }}</td>
                            <td><span class="glyphicon glyphicon-arrow-right" aria-hidden="true"></span></td>
                            <td>{{ productMoving.to }}</td>
                            <td>{{ productMoving.quantity }}</td>
                            <td>
                                {% set editRouteName = 'spolischook_minishop_' ~ productMoving.getRouterChunkClassName ~ '_formedit' %}
                                <a href="{{ path(editRouteName, {'id': productMoving.id}) }}" type="button" class="btn btn-default" aria-label="Left Align">
                                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Edit
                                </a>
                                <a href="#" data-action="{{ path('spolischook_minishop_' ~ productMoving.getRouterChunkClassName ~ '_delete', {'id': productMoving.id}) }}" type="submit" class="btn btn-danger delete-product-moving" aria-label="Left Align">
                                    <span class="glyphicon glyphicon-trash" aria-hidden="true"></span> Delete
                                </a>
                            </td>
                        </tr>
                    {% set previousProductMoving = productMoving %}
                {% endfor %}
            </table>
        </div>
    </div>
{% endblock %}
{% block javascripts %}
    {{ parent() }}
    <script src="//cdnjs.cloudflare.com/ajax/libs/handlebars.js/2.0.0/handlebars.min.js"></script>
    <script id="some-template" type="text/x-handlebars-template">
        {% raw %}
        <table class="table">
            <tr>
                <th>Дата</th>
                <th></th>
                <th>From</th>
                <th></th>
                <th>To</th>
                <th>Количество</th>
                <th>Actions</th>
            </tr>
            <tbody>
            {{#productMovings}}
            <tr>
                <td>{{ created_at }}</td>
                <td>{{{getIcon router_chunk_class_name}}}</td>
                <td>{{ from }}</td>
                <td><span class="glyphicon glyphicon-arrow-right" aria-hidden="true"></span></td>
                <td>{{ to }}</td>
                <td>{{ quantity }}</td>
                <td></td>
            </tr>
            {{/productMovings}}
            </tbody>
        </table>
        {% endraw %}
    </script>
    <script>
        var data = {{ productMovings|raw }}
        var source = $("#some-template").html();
        var template = Handlebars.compile(source);
        Handlebars.registerHelper('getIcon', function(routeChunkClassName) {
            var routeChunkClassName = Handlebars.escapeExpression(routeChunkClassName),
                    icoClassChunk;

            if ('producttransfer' == routeChunkClassName) {
                icoClassChunk = 'transfer';
            }

            return new Handlebars.SafeString(
                    '<span class="glyphicon glyphicon-' + icoClassChunk + '" aria-hidden="true"></span>'
            );
        });
        $('div#view-data').append(template(data));


        $( document ).ready(function() {
            $( ".delete-product-moving" ).click(function(e) {
                e.preventDefault();
                var agreement=confirm('{{ 'are_you_sure_you_whant_to_delete_this_item'|trans }}');

                if (false == agreement) {
                    return;
                }

                var deleteButton = this;

                $.ajax({
                    url: $(this).data('action'),
                    type: "DELETE",
                    dataType : "json",
                    success: function( json ) {
                        $(deleteButton).closest('tr').remove();
                    },
                    error: function( xhr, status, errorThrown ) {
                        alert('Oops, something went wrong');
                    }
                });
            });
        });
    </script>
{% endblock %}