src/Spolischook/MiniShopBundle/Entity/Store.php
<?php

namespace Spolischook\MiniShopBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Store
 *
 * @ORM\Table(name="store")
 * @ORM\Entity(repositoryClass="Spolischook\MiniShopBundle\Repository\StoreRepository")
 */
class Store
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="title", type="string", length=255)
     * @Assert\NotBlank()
     */
    private $title;

    /**
     * @Gedmo\Slug(fields={"title"})
     * @ORM\Column(name="slug", type="string", length=255)
     */
    private $slug;

    /**
     * @var integer
     *
     * @ORM\Column(name="product_quantity", type="integer", nullable=true)
     * @Assert\GreaterThanOrEqual(value = 0)
     */
    private $productQuantity;

    /**
     * @var
     *
     * @ORM\ManyToOne(targetEntity="Spolischook\MiniShopBundle\Entity\Product", inversedBy="stores")
     */
    private $product;

    /**
     * @var \Spolischook\MiniShopBundle\Entity\ProductSale
     *
     * @ORM\OneToMany(targetEntity="Spolischook\MiniShopBundle\Entity\ProductSale", mappedBy="store", fetch="EAGER")
     */
    private $productSales;

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->productSales = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set title
     *
     * @param string $title
     * @return Store
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title
     *
     * @return string 
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set productQuantity
     *
     * @param integer $productQuantity
     * @return Store
     */
    public function setProductQuantity($productQuantity)
    {
        $this->productQuantity = $productQuantity;

        return $this;
    }

    /**
     * Get productQuantity
     *
     * @return integer 
     */
    public function getProductQuantity()
    {
        return $this->productQuantity;
    }

    /**
     * Set product
     *
     * @param \Spolischook\MiniShopBundle\Entity\Product $product
     * @return Store
     */
    public function setProduct(\Spolischook\MiniShopBundle\Entity\Product $product = null)
    {
        $this->product = $product;

        return $this;
    }

    /**
     * Get product
     *
     * @return \Spolischook\MiniShopBundle\Entity\Product 
     */
    public function getProduct()
    {
        return $this->product;
    }

    /**
     * Set slug
     *
     * @param string $slug
     * @return Store
     */
    public function setSlug($slug)
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * Get slug
     *
     * @return string 
     */
    public function getSlug()
    {
        return $this->slug;
    }

    /**
     * Add productSales
     *
     * @param \Spolischook\MiniShopBundle\Entity\ProductSale $productSales
     * @return Store
     */
    public function addProductSale(\Spolischook\MiniShopBundle\Entity\ProductSale $productSales)
    {
        $this->productSales[] = $productSales;

        return $this;
    }

    /**
     * Remove productSales
     *
     * @param \Spolischook\MiniShopBundle\Entity\ProductSale $productSales
     */
    public function removeProductSale(\Spolischook\MiniShopBundle\Entity\ProductSale $productSales)
    {
        $this->productSales->removeElement($productSales);
    }

    /**
     * Get productSales
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getProductSales()
    {
        return $this->productSales;
    }

    /**
     * @return int
     */
    public function getGiftItemsCount()
    {
        $giftItems = 0;

        /** @var ProductSale $productSale */
        foreach ($this->getProductSales() as $productSale) {
            if ($productSale->getPrice() == 0) {
                $giftItems += $productSale->getQuantity();
            }
        }

        return $giftItems;
    }

    /**
     * @return int
     */
    public function getSalesItemsCount()
    {
        $salesItems = 0;

        /** @var ProductSale $productSale */
        foreach ($this->getProductSales() as $productSale) {
            if ($productSale->getPrice() > 0) {
                $salesItems += $productSale->getQuantity();
            }
        }

        return $salesItems;
    }

    public function __toString()
    {
        return $this->getTitle();
    }
}

src/Spolischook/MiniShopBundle/Resources/views/Index/index.html.twig
{% extends '::base.html.twig' %}

{% block title %}Минишоп{% endblock %}
{% block container %}
    <h2>{{ product.title }}</h2>
    <div class="row">
        <div class="col-md-8">
            <h3>Cклады</h3>
            <table class="table">
                <tr>
                    <th>Склад</th>
                    <th>Остаток</th>
                    <th>Продано</th>
                    <th>Подарено</th>
                    <th>Экшины</th>
                </tr>
                {% for store in stores %}
                    <tr>
                        <td><a href="{{ path('spolischook_minishop_store_get', {'slug': store.slug}) }}">{{ store.title }}</a></td>
                        <td>{{ store.productQuantity }}</td>
                        <td>{{ store.salesItemsCount }}</td>
                        <td>{{ store.giftItemsCount }}</td>
                        <td>
                            {% if store.productQuantity > 0 %}
                                <a href="{{ path('spolischook_minishop_productsale_formnew', {'slug': store.slug }) }}" type="button" class="btn btn-default" aria-label="Left Align">
                                    <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span> Продать
                                </a>
                                <a href="{{ path('spolischook_minishop_producttransfer_formnew', {'slug': store.slug }) }}" type="button" class="btn btn-default" aria-label="Left Align">
                                    <span class="glyphicon glyphicon-transfer" aria-hidden="true"></span> Переместить
                                </a>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </div>
        <div class="col-md-4">
            <h3>Итог</h3>
            <table class="table">
                <tr>
                    <th>Название</th>
                    <th>Количество</th>
                </tr>
                <tr>
                    <td>Всего остаток:</td>
                    <td>{{ totalInStores }} шт</td>
                </tr>
                <tr>
                    <td>Всего наличными:</td>
                    <td>
                        {{ cashBank.total }} грн
                        {% if (cashBank.total > 0) %}
                            &nbsp<a href="{{ path('spolischook_minishop_moneytransfer_formnew', {'id': cashBank.id }) }}" type="button" class="btn btn-default" aria-label="Left Align">
                                <span class="glyphicon glyphicon-random" aria-hidden="true"></span> Переместить
                            </a>
                        {% endif %}
                    </td>
                </tr>
                <tr>
                    <td>Всего на карту:</td>
                    <td>
                        {{ cardBank.total }} грн
                        {% if (cardBank.total > 0) %}
                            &nbsp<a href="{{ path('spolischook_minishop_moneytransfer_formnew', {'id': cardBank.id }) }}" type="button" class="btn btn-default" aria-label="Left Align">
                            <span class="glyphicon glyphicon-random" aria-hidden="true"></span> Переместить
                        </a>
                        {% endif %}
                    </td>
                </tr>
                <tr>
                    <td>Всего продано:</td>
                    <td>{{ totalSales }} шт</td>
                </tr>
                <tr>
                    <td>Всего подарено:</td>
                    <td>{{ totalGifts }} шт</td>
                </tr>
            </table>
        </div>
    </div>
{% endblock %}